/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drones.interfaz;

import javax.swing.*;

import java.awt.Color;
import java.awt.Insets;
import javax.swing.JButton;

/**
 *
 * @author nrusso
 */
public class IngresoEgresoCarga extends javax.swing.JFrame {

    /**
     * Creates new form IngresoEgresoCarga
     */
    public IngresoEgresoCarga() {
        initComponents();
        for (int i = 0; i < 12; i++) {
                    for (int j = 0; j < 10; j++) {                       
                        JButton nuevo = new JButton(" ");
                        nuevo.setMargin(new Insets(-5, -5, -5, -5));
                        nuevo.setBackground(Color.BLACK);
                        nuevo.setForeground(Color.WHITE);
                        nuevo.setText( "texto"); // texto ejemplo, a completar
                        //nuevo.addActionListener(new EspacioListener());
                        ButtonsGrid.add(nuevo);                        
                    }                    
                }                               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        Area = new javax.swing.JLabel();
        ButtonsPanel = new javax.swing.JPanel();
        XLabels = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        XLabel1 = new javax.swing.JLabel();
        XLabel2 = new javax.swing.JLabel();
        XLabel3 = new javax.swing.JLabel();
        XLabel4 = new javax.swing.JLabel();
        XLabel5 = new javax.swing.JLabel();
        XLabel6 = new javax.swing.JLabel();
        XLabel7 = new javax.swing.JLabel();
        XLabel8 = new javax.swing.JLabel();
        XLabel9 = new javax.swing.JLabel();
        XLabel10 = new javax.swing.JLabel();
        YLabels = new javax.swing.JPanel();
        YLabel1 = new javax.swing.JLabel();
        YLabel2 = new javax.swing.JLabel();
        YLabel3 = new javax.swing.JLabel();
        YLabel4 = new javax.swing.JLabel();
        YLabel5 = new javax.swing.JLabel();
        YLabel6 = new javax.swing.JLabel();
        YLabel7 = new javax.swing.JLabel();
        YLabel8 = new javax.swing.JLabel();
        YLabel9 = new javax.swing.JLabel();
        YLabel10 = new javax.swing.JLabel();
        YLabel11 = new javax.swing.JLabel();
        YLabel12 = new javax.swing.JLabel();
        ButtonsGrid = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PreviousAreaButton = new javax.swing.JButton();
        NextAreaButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        LeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        LeftPanel.setLayout(new java.awt.BorderLayout());

        Area.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Area.setText("Area: A");
        LeftPanel.add(Area, java.awt.BorderLayout.NORTH);

        ButtonsPanel.setLayout(new java.awt.BorderLayout());

        XLabels.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        XLabels.setLayout(new java.awt.GridLayout(1, 11));
        XLabels.add(filler1);

        XLabel1.setText("1");
        XLabels.add(XLabel1);

        XLabel2.setText("2");
        XLabels.add(XLabel2);

        XLabel3.setText("3");
        XLabels.add(XLabel3);

        XLabel4.setText("4");
        XLabels.add(XLabel4);

        XLabel5.setText("5");
        XLabels.add(XLabel5);

        XLabel6.setText("6");
        XLabels.add(XLabel6);

        XLabel7.setText("7");
        XLabels.add(XLabel7);

        XLabel8.setText("8");
        XLabels.add(XLabel8);

        XLabel9.setText("9");
        XLabels.add(XLabel9);

        XLabel10.setText("10");
        XLabels.add(XLabel10);

        ButtonsPanel.add(XLabels, java.awt.BorderLayout.NORTH);

        YLabels.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        YLabels.setLayout(new java.awt.GridLayout(12, 1));

        YLabel1.setText("1");
        YLabels.add(YLabel1);

        YLabel2.setText("2");
        YLabels.add(YLabel2);

        YLabel3.setText("3");
        YLabels.add(YLabel3);

        YLabel4.setText("4");
        YLabels.add(YLabel4);

        YLabel5.setText("5");
        YLabels.add(YLabel5);

        YLabel6.setText("6");
        YLabels.add(YLabel6);

        YLabel7.setText("7");
        YLabels.add(YLabel7);

        YLabel8.setText("8");
        YLabels.add(YLabel8);

        YLabel9.setText("9");
        YLabels.add(YLabel9);

        YLabel10.setText("10");
        YLabels.add(YLabel10);

        YLabel11.setText("11");
        YLabels.add(YLabel11);

        YLabel12.setText("12");
        YLabels.add(YLabel12);

        ButtonsPanel.add(YLabels, java.awt.BorderLayout.WEST);

        ButtonsGrid.setLayout(new java.awt.GridLayout(12, 10));
        ButtonsPanel.add(ButtonsGrid, java.awt.BorderLayout.CENTER);

        LeftPanel.add(ButtonsPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        PreviousAreaButton.setText("<<<");
        PreviousAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousAreaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(PreviousAreaButton);

        NextAreaButton.setText(">>>");
        NextAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextAreaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(NextAreaButton);

        LeftPanel.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(LeftPanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreviousAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousAreaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviousAreaButtonActionPerformed

    private void NextAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextAreaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextAreaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoEgresoCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoEgresoCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoEgresoCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoEgresoCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                        
                new IngresoEgresoCarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Area;
    private javax.swing.JPanel ButtonsGrid;
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton NextAreaButton;
    private javax.swing.JButton PreviousAreaButton;
    private javax.swing.JLabel XLabel1;
    private javax.swing.JLabel XLabel10;
    private javax.swing.JLabel XLabel2;
    private javax.swing.JLabel XLabel3;
    private javax.swing.JLabel XLabel4;
    private javax.swing.JLabel XLabel5;
    private javax.swing.JLabel XLabel6;
    private javax.swing.JLabel XLabel7;
    private javax.swing.JLabel XLabel8;
    private javax.swing.JLabel XLabel9;
    private javax.swing.JPanel XLabels;
    private javax.swing.JLabel YLabel1;
    private javax.swing.JLabel YLabel10;
    private javax.swing.JLabel YLabel11;
    private javax.swing.JLabel YLabel12;
    private javax.swing.JLabel YLabel2;
    private javax.swing.JLabel YLabel3;
    private javax.swing.JLabel YLabel4;
    private javax.swing.JLabel YLabel5;
    private javax.swing.JLabel YLabel6;
    private javax.swing.JLabel YLabel7;
    private javax.swing.JLabel YLabel8;
    private javax.swing.JLabel YLabel9;
    private javax.swing.JPanel YLabels;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
