/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drones.interfaz;

import drones.dominio.Dron;
import drones.dominio.Sistema;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Franc
 */
public class RegistrarDron extends javax.swing.JFrame {
    
    private Sistema sistema;

    /**
     * Creates new form RegistrarDron
     */
    public RegistrarDron() {
        initComponents();
    }
    
    public RegistrarDron (Sistema s) {
    this.sistema = s;
    initComponents();
    hydrate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlIngresoDatos = new javax.swing.JPanel();
        lblIdentificacion = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        pnlDatosDron = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        java.awt.GridBagLayout pnlIngresoDatosLayout = new java.awt.GridBagLayout();
        pnlIngresoDatosLayout.columnWidths = new int[] {0, 31, 0, 31, 0, 31, 0, 31, 0, 31, 0, 31, 0};
        pnlIngresoDatosLayout.rowHeights = new int[] {0, 54, 0, 54, 0, 54, 0};
        pnlIngresoDatos.setLayout(pnlIngresoDatosLayout);

        lblIdentificacion.setText("Identificación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlIngresoDatos.add(lblIdentificacion, gridBagConstraints);

        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlIngresoDatos.add(txtIdentificacion, gridBagConstraints);

        lblModelo.setText("Modelo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlIngresoDatos.add(lblModelo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlIngresoDatos.add(txtModelo, gridBagConstraints);

        lblTipo.setText("Tipo de Cámara");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlIngresoDatos.add(lblTipo, gridBagConstraints);

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlIngresoDatos.add(txtTipo, gridBagConstraints);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlIngresoDatos.add(btnAgregar, gridBagConstraints);

        getContentPane().add(pnlIngresoDatos);

        tblDrones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificación", "Modelo", "Tipo de Cámara"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrones);
        if (tblDrones.getColumnModel().getColumnCount() > 0) {
            tblDrones.getColumnModel().getColumn(0).setResizable(false);
            tblDrones.getColumnModel().getColumn(1).setResizable(false);
            tblDrones.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pnlDatosDronLayout = new javax.swing.GroupLayout(pnlDatosDron);
        pnlDatosDron.setLayout(pnlDatosDronLayout);
        pnlDatosDronLayout.setHorizontalGroup(
            pnlDatosDronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosDronLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        pnlDatosDronLayout.setVerticalGroup(
            pnlDatosDronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosDronLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlDatosDron);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(txtIdentificacion.getText().equals("") ||
           txtModelo.getText().equals("") ||
           !Pattern.matches("[0-9]+", txtTipo.getText()) ||
           txtTipo.getText().equals("")) {
        
        JOptionPane.showMessageDialog(null, "Campos Incorrectos",
                "Error", JOptionPane.ERROR_MESSAGE);        
        } else {
            this.sistema.agregarDron(txtIdentificacion.getText(),
                    txtModelo.getText(),
                    Integer.parseInt(txtTipo.getText()));                        
            
            hydrate();            
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void hydrate () {
        ArrayList<Dron> drones = this.sistema.getDrones();
        
        DefaultTableModel tblModel = (DefaultTableModel) tblDrones.getModel();
        
        tblModel.setRowCount(0);
        
        for (int i = 0; i < drones.size(); i++) {            
            String[] row = {drones.get(i).getIdentificacion(),
                            drones.get(i).getModelo(),
                            String.valueOf(drones.get(i).getCamara())};
            
            tblModel.addRow(row);            
        }
        
        txtIdentificacion.setText("");
        txtModelo.setText("");
        txtTipo.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlDatosDron;
    private javax.swing.JPanel pnlIngresoDatos;
    private javax.swing.JTable tblDrones;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
