/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drones.interfaz;

import drones.dominio.Dron;
import drones.dominio.Sistema;
import java.util.ArrayList;

/**
 *
 * @author Franc
 */
public class Statistics extends javax.swing.JFrame {
    
    private Sistema sistema;

    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
    }
    
    public Statistics (Sistema sistema){
        this.sistema = sistema;
        initComponents();
        hydrate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDronesConVuelos = new javax.swing.JPanel();
        lblDronesConVuelos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDronesConVuelos = new javax.swing.JList<>();
        pnlInfoVuelos = new javax.swing.JPanel();
        lblInformacionVuelos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstInfoVuelos = new javax.swing.JList<>();
        pnlDronesSinVuelos = new javax.swing.JPanel();
        lblDronesSinVuelos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDronesSinVuelos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        pnlDronesConVuelos.setLayout(new java.awt.BorderLayout());

        lblDronesConVuelos.setText("Drones con vuelos");
        pnlDronesConVuelos.add(lblDronesConVuelos, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(lstDronesConVuelos);

        pnlDronesConVuelos.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDronesConVuelos);

        pnlInfoVuelos.setLayout(new java.awt.BorderLayout());

        lblInformacionVuelos.setText("Informacion vuelos");
        pnlInfoVuelos.add(lblInformacionVuelos, java.awt.BorderLayout.NORTH);

        jScrollPane2.setViewportView(lstInfoVuelos);

        pnlInfoVuelos.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlInfoVuelos);

        pnlDronesSinVuelos.setLayout(new java.awt.BorderLayout());

        lblDronesSinVuelos.setText("Drones sin vuelos");
        pnlDronesSinVuelos.add(lblDronesSinVuelos, java.awt.BorderLayout.NORTH);

        jScrollPane3.setViewportView(lstDronesSinVuelos);

        pnlDronesSinVuelos.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDronesSinVuelos);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDronesConVuelos;
    private javax.swing.JLabel lblDronesSinVuelos;
    private javax.swing.JLabel lblInformacionVuelos;
    private javax.swing.JList<String> lstDronesConVuelos;
    private javax.swing.JList<String> lstDronesSinVuelos;
    private javax.swing.JList<String> lstInfoVuelos;
    private javax.swing.JPanel pnlDronesConVuelos;
    private javax.swing.JPanel pnlDronesSinVuelos;
    private javax.swing.JPanel pnlInfoVuelos;
    // End of variables declaration//GEN-END:variables

    private void hydrate() {
        ArrayList<Dron> drones = this.sistema.getDrones();        
        
        lstDronesConVuelos.setListData(drones.stream()
        .filter(d -> !d.getVuelos().isEmpty()).map(d -> d.toString()).toArray(String[]::new));
        
        lstDronesSinVuelos.setListData(drones.stream()
        .filter(d -> d.getVuelos().isEmpty()).map(d -> d.toString()).toArray(String[]::new));
        
        
    }
}
